app:
  app_name: "HDU-QA-Platform"
  version: "v1.0.1"
  port: 8082
  run_mode: dev

db:
  host: "localhost"
  port: 33061
  user: "root"
  password: "3223061"
  dbname: "qa-platform"
  max_idle_conn: 5
  max_open_conn: 20
  max_idle_time: 300

redis:
  rhost: "localhost"
  rport: 6379
  rdb: 0
  passwd: ''
  poolsize: 100

cache:
  session_expired: 7200
  user_expired: 300